// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuQDGs9l6tcq-cXXMMPgSoNw-8NI5kf2w',
    appId: '1:269638034505:web:fb73ead60107ef8aa20b98',
    messagingSenderId: '269638034505',
    projectId: 'homeservices-bc6e5',
    authDomain: 'homeservices-bc6e5.firebaseapp.com',
    storageBucket: 'homeservices-bc6e5.firebasestorage.app',
    measurementId: 'G-DW00Q86PG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8fpB-5NJTGre9Vf7UfH1BtWKaG9dw0CM',
    appId: '1:269638034505:android:9fab63dc45f06203a20b98',
    messagingSenderId: '269638034505',
    projectId: 'homeservices-bc6e5',
    storageBucket: 'homeservices-bc6e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBcZ9esRYlJUSqNKtm87Ml8_FiT-7IbIE',
    appId: '1:269638034505:ios:aac8e747a0e9e601a20b98',
    messagingSenderId: '269638034505',
    projectId: 'homeservices-bc6e5',
    storageBucket: 'homeservices-bc6e5.firebasestorage.app',
    iosBundleId: 'com.example.homeServicesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBcZ9esRYlJUSqNKtm87Ml8_FiT-7IbIE',
    appId: '1:269638034505:ios:aac8e747a0e9e601a20b98',
    messagingSenderId: '269638034505',
    projectId: 'homeservices-bc6e5',
    storageBucket: 'homeservices-bc6e5.firebasestorage.app',
    iosBundleId: 'com.example.homeServicesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuQDGs9l6tcq-cXXMMPgSoNw-8NI5kf2w',
    appId: '1:269638034505:web:5d1ab23f4c2fb887a20b98',
    messagingSenderId: '269638034505',
    projectId: 'homeservices-bc6e5',
    authDomain: 'homeservices-bc6e5.firebaseapp.com',
    storageBucket: 'homeservices-bc6e5.firebasestorage.app',
    measurementId: 'G-556V335K9M',
  );
}
